blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://talk.openelis-global.org/
    about: Get help from the OpenELIS Global community on our talk forum.
  - name: Contribution Guide
    url: https://github.com/DIGI-UW/OpenELIS-Global-2/blob/develop/CONTRIBUTING.md
    about: Learn how to get started with contributing to OpenELIS Global 2.
